# Generated by Django 5.0.3 on 2024-03-05 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_auction_updated_at_bid_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 3, 5, 21, 40, 39, 720973, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
