# Generated by Django 5.0.3 on 2024-03-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bid_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
